// Code generated by "stringer -type=AudioFormat"; DO NOT EDIT.

package wave

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PCM-1]
}

const _AudioFormat_name = "PCM"

var _AudioFormat_index = [...]uint8{0, 3}

func (i AudioFormat) String() string {
	i -= 1
	if i >= AudioFormat(len(_AudioFormat_index)-1) {
		return "AudioFormat(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _AudioFormat_name[_AudioFormat_index[i]:_AudioFormat_index[i+1]]
}
